image: node:10.15.3

clone:
  depth: full

pipelines:
  pull-requests:
    feature/*:
      - step:
          size: 2x
         # caches:
           # - node
           # - sonar
          services:
            - docker
          script:
            # - echo "running test coverage"
            # - go run test
            # - echo "Sonarcloud running ..."
            # - pipe: sonarsource/sonarcloud-scan:1.2.0
            # - pipe: sonarsource/sonarcloud-quality-gate:0.1.4
            - echo "Running for branch" $BITBUCKET_BRANCH
            - git remote add ripley https://$codeCommitUserSnx:$codeCommitPassSnx@$codeCommitUrlSnx
            - git push ripley HEAD:$BITBUCKET_BRANCH -f

  branches:
    dev:
      - step:
          size: 2x
         # caches:
           # - node
           # - sonar
          script:
            # - echo "running test coverage"
            # - go run test
            # - echo "Sonarcloud running ..."
            # - pipe: sonarsource/sonarcloud-scan:1.2.0
            # - pipe: sonarsource/sonarcloud-quality-gate:0.1.4
            - echo "Installing  jq ..."
            - apt-get update && apt-get install jq -y
            - urlencodedPass=$(echo $codeCommitPassQa | jq -R -r @uri)
            - echo "Running for branch" $BITBUCKET_BRANCH
            - git remote add ripley https://$codeCommitUserQa:$urlencodedPass@$codeCommitUrlQa
            - git push ripley HEAD:$BITBUCKET_BRANCH -f

    prod:
      - step:
          size: 2x
         # caches:
          #  - node
          #  - sonar
          script:
            # - echo "running test coverage"
            # - go run test
            # - echo "Sonarcloud running ..."
            # - pipe: sonarsource/sonarcloud-scan:1.2.0
            # - pipe: sonarsource/sonarcloud-quality-gate:0.1.4
            - echo "Running for branch" $BITBUCKET_BRANCH
            - git remote add ripley https://$codeCommitUserProd:$codeCommitPassProd@$codeCommitUrlProd
            - git push ripley HEAD:$BITBUCKET_BRANCH -f

definitions:
 # caches:
  #  sonar: ~/.sonar/cache
  services:
    docker:
      memory: 2048
