version: '3.8'
services:
  golang:
    container_name: golang-kafka-producer
    image: golang:golang-kafka-producer
    env_file:
      - .env
    build:
      context: ./
      target: production
    #command: go run src/main.go
    #volumes:
    # - ./:/app
    networks:
      - default
      - database-network
      - backend-network
      - kafka-network
    ports:
      - "4000:3000"

networks:
  default:
    driver: bridge
  database-network:
    external:
      name: database-network
  backend-network:
    external:
      name: backend-network
  kafka-network:
    external:
      name: kafka-network

