version: '3.8'
services:
  golang:
    container_name: wrk-conector-producer
    image: golang:wrk-conector-producer
    env_file:
      - .env
    build:
      context: ./
      target: development
    working_dir: /app
    volumes:
      - ./:/app
    command: yarn run start:dev
    networks:
      - default
      - db-network
    ports:
      - "4000:3000"

networks:
  default:
    external:
      name: backend-network
  db-network:
    external:
      name: db-network
