version: '3.8'
services:
  golang:
    container_name: wrk-connector
    image: golang:wrk-connector
    env_file:
      - .env
    build:
      context: ./
      target: development
    working_dir: /app
    volumes:
      - ./:/app
    command: yarn run start:dev
    restart: always
    networks:
      - default
    ports:
      - "4000:3000"

networks:
  default:
    external:
      name: backend-network
